CREATE TABLE IF NOT EXISTS orig (  
  TS_CODE	  TIMESTAMP NOT NULL,
  ID_ORIG_H   VARCHAR,    
  PROTO 	  VARCHAR,
  SERVICE     VARCHAR,
  DURATION    UNSIGNED_LONG,
  ORIG_BYTES  UNSIGNED_LONG,
  RESP_BYTES  UNSIGNED_LONG,
	  
  CONSTRAINT pk PRIMARY KEY( TS_CODE,
							 ID_ORIG_H
							 PROTO  ,
							 SERVICE ));
